name: Enhancement
description: User-facing new features, new capabilites or UX improvements to existing features, etc.
labels: ["enhancement"]
projects: ["workbrew/1"]
body:
  - type: markdown
    attributes:
      value: |
        - Please add the following labels:
            - `console`, `agent` or `homebrew`
            - A `size: ` label
            - Any other relevant labels
  - type: textarea
    id: repro
    attributes:
      label: Describe the problem and/or link back to an issue on https://github.com/Workbrew/market-feedback
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
