name: Enhancement
description: User-facing new features, new capabilites or UX improvements to existing features, etc.
labels: ["enhancement"]
projects: ["workbrew/1"]
body:
  - type: markdown
    attributes:
      value: |
        - Please add the following labels:
            - `console`, `agent` or `homebrew`
            - A `size: ` label
            - Any other relevant labels
  - type: textarea
    attributes:
      label: Describe the problem
      description: "If possible, link back to an issue on [/market-feedback](https://github.com/Workbrew/market-feedback)"
  - type: textarea
    attributes:
      label: What solution do you think is best and what will be the impact?
      description: "test"
