name: Bug
description: Something doesn't work as it should or has regressed in behaviour 
labels: ["bug"]
projects: ["workbrew/1"]
body:
  - type: markdown
    attributes:
      value: |
        - What steps can be taken to recreate this and what is the expected behaviour? 🐞
        - Provide before/after screenshots if this is a UI change 🖼️
        - Add any relevant labels 🏷️
        - Add any other useful context 🗺️
  - type: textarea
    attributes:
      label: Issue description
