name: Bug
description: Something doesn't work as it should or has regressed in behaviour 
labels: ["bug"]
projects: ["workbrew/1"]
body:
  - type: textarea
    attributes:
      label: What were you trying to do (and why)?
  - type: textarea
    attributes:
      label: What happened?
      description: "Please add any relevant screenshots, gifs or troubleshooting data."
  - type: textarea
    attributes:
      label: What did you expect to happen?
  - type: textarea
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please provide step by step instructions."
      value: |
        1.
        2.
        3.
        ...
