name: Bug
description: Something doesn't work as it should or has regressed in behaviour 
labels: ["bug"]
projects: ["workbrew/1"]
body:
  - type: markdown
    attributes:
      value: |
        - What steps can be taken to recreate this and what is the expected behaviour? 🐞
        - Provide before/after screenshots if this is a UI change 🖼️
        - Add any relevant labels 🏷️
        - Add any other useful context 🗺️
  - type: textarea
    attributes:
      label: What were you trying to do (and why)?
  - type: textarea
    attributes:
      label: What happened?
  - type: textarea
    attributes:
      label: What did you expect to happen?
  - type: textarea
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
