name: Maintenance
description: "All non-user visible work such as: Infrastructure, performance, security, compliance etc."
projects: ["workbrew/1"]
body:
  - type: markdown
    attributes:
      value: |
        - Please add the following labels:
            - `console`, `agent` or `homebrew`
            - A `size: ` label
            - Any other relevant labels
  - type: textarea
    attributes:
      label: Describe the problem
  - type: textarea
    attributes:
      label: What solution do you propose and what will be the impact?
  - type: textarea
    attributes:
      label: Any other useful context 
