name: Product Discovery Issue
description: Identifying and validating customer needs to guide product development
title: "[Succinct, high-level outcome for users]" 
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Please add requestors in a new comment with as much context as possible
        👋 Labels are cheap and help to draw connections between product themes. Go nuts →
  - type: textarea
    attributes:
      label: Why?
      description: "More details on the *outcome(s)* for users this enables."
      placeholder: "e.g. [Persona] need to be able to [something] because they have [problem]."
  - type: textarea
    attributes:
      label: What?
      description: "What is being suggested? What is the user-flow?"
  - type: textarea
    attributes:
      label: Additional thoughts/questions
