name: Homebrew
description: Something that will require changes in Homebrew 
labels: ["homebrew"]
projects: ["workbrew/1"]
body:
  - type: markdown
    attributes:
      value: |
        - Add any relevant labels 🏷️
        - Add any other useful context 🗺️
  - type: textarea
    attributes:
      label: Issue description
