name: Enhancement
description: User-facing new features, new capabilites or UX improvements to existing features, etc.
type: ["no type"]
projects: ["workbrew/1"]
body:
  - type: markdown
    attributes:
      value: |
        - Please add the following labels:
            - `console`, `agent` or `homebrew`
            - A `size: ` label
            - Any other relevant labels
  - type: textarea
    attributes:
      label: Describe the problem
      description: "When possible, link back to an issue on [/product-discovery](https://github.com/Workbrew/product-discovery)"
  - type: textarea
    attributes:
      label: What solution do you propose and what will be the impact?
      description: "Also list any alternative solutions you've considered"
  - type: textarea
    attributes:
      label: Any other useful context
      description: "User flows, external links, quotes etc."
