name: Epic
description: Parent-issue for a theme we want to ship over a shape-up cycle
projects: ["workbrew/1"]
labels: ["🦑 size: large"]
body:
  - type: markdown
    attributes:
      value: |
        Please add any other relevant labels →
  - type: textarea
    attributes:
      label: Theme & Goals
      description: "What is the high-level goal of this Epic? Define the high-level problems and what success looks like and link to any and all related issues on [/product-discovery](https://github.com/Workbrew/product-discovery/issues) so that readers can learn more about the outcomes we're building for."
  - type: textarea
    attributes:
      label: Sub-Issues
      description: "List the related issues that contribute to this Epic."
      value: |
        - [ ] #issue-link-1
        - [ ] #issue-link-2
  - type: textarea
    attributes:
      label: End-to-End User Flows
      description: "Describe the ideal user experiences in a bulleted list. Consider describing both the Admin and End-User experience if applicable."
  - type: textarea
    attributes:
      label: Rollout
      description: "What’s the rollout strategy (e.g. staff-ship, straight to public-ship, private beta with a customer) and what plan does it target?"
      placeholder:  |
        Examples:
        - Staff-ship while we dogfood before publicly shipping
        - Enterprise plan only
  - type: textarea
    attributes:
      label: Documentation
      description: "Will there be in-app or [standalone](https://console.workbrew.com/documentation) docs that need updating?"
