name: Product Discovery Issue
description: Identifying and validating customer needs to guide product development
title: "[Succinct, high-level outcome for users]" 
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Please add customer requests in a new comment with as much context as possible
        
        🏷️ Labels are cheap and help to draw connections between product themes. Go nuts →
  - type: textarea
    attributes:
      label: Outcome(s) for users this enables
      description: |
        Provide as many detials on 'the Whys' and problem statements behind this as you can
        It's ok if the outcomes are fuzzy – we can keep exploring, discussing and updating the orginal issue description
      placeholder: "e.g. [Persona] need to be able to [something] because they have [problem]."
  - type: textarea
    attributes:
      label: Non-perscriptuive suggestions for what might get us to the user outcomes
      description: |
        Help us understand the outcomes by painting a picture of the solution space
        For example: What is being suggested? What might a user-flow look like?
  - type: textarea
    attributes:
      label: Additional thoughts/questions
